# aliases
alias devenv="sudo arkose -n -h"
alias gk='gitk --all &'

# edit remote file locally
alias rsub='rmate -p 52699'

# clean up go path
alias gocls="rm -rf $GOPATH/pkg/*"

alias ssx='ssh -X'
# ssh compression and blowfish encrpytion for faster throughput
alias sscx='ssh -C -X -c blowfish'
